# 🌡️ Heatwave Analyzer using NumPy

Welcome to the **Heatwave Analyzer**! This project simulates daily temperature data for 60 days and analyzes weekly patterns, extreme heat events, and sudden temperature spikes using `NumPy`.

🧠 **Skills Covered:** `reshape`, `mean`, `where`, `argmax`, `unravel_index`, `diff`

📅 **Timeline:** Day 1 & 2 of #Warpath28 

🗣️ Completed on `day 2`!

In [2]:
import numpy as np

## 1️⃣ Step 1: Lets Generate Daily Temperature Data

We use NumPy to generate random temperatures for 60 days.  
Temperature range: **22°C to 43°C**.

In [3]:
Daily_temp = np.random.randint(22, 43, size=(60))
print("Daily Temp: ", Daily_temp)

Daily Temp:  [25 32 25 37 42 34 39 32 31 40 23 36 35 34 23 36 30 27 41 28 33 34 22 34
 22 31 33 35 24 41 22 29 24 34 25 28 22 40 28 36 34 22 38 35 42 26 36 22
 35 38 32 36 33 28 32 34 37 28 25 31]


## Step 2: Reshape Data into Weeks

We divide the 60-day data into **10 weeks**, with each week having 6 days.
We’ll reshape our array into a `(10, 6)` shape.

In [4]:
weeks= Daily_temp.reshape(10, 6)
print(weeks)

[[25 32 25 37 42 34]
 [39 32 31 40 23 36]
 [35 34 23 36 30 27]
 [41 28 33 34 22 34]
 [22 31 33 35 24 41]
 [22 29 24 34 25 28]
 [22 40 28 36 34 22]
 [38 35 42 26 36 22]
 [35 38 32 36 33 28]
 [32 34 37 28 25 31]]


## Step 3: Calculate Weekly Averages

We calculate the **average temperature** for each week using `np.mean()` along `axis=1`.
This helps us identify how hot or cold each week was overall.

In [5]:
average= np.mean(weeks, axis=1)
print(f'The average Temp is:{average}')

The average Temp is:[32.5        33.5        30.83333333 32.         31.         27.
 30.33333333 33.16666667 33.66666667 31.16666667]


## Step 4: Detect Heatwave Weeks

A heatwave is defined as a week with an **average temperature > 35°C**.  
We use `np.where()` to detect such weeks.
And also do +1 when printing for readability.

In [6]:
hot_weeks= np.where(average>35)[0] 
print("Heatwave weeks (avg>35): ", hot_weeks+1) 

Heatwave weeks (avg>35):  []


## Step 5: Find the Hottest Day

Let’s find:
- The **maximum temperature**
- The **week and day** it occurred

We use `np.argmax()` to locate the max, and `np.unravel_index()` to translate it into week/day format.


In [13]:
Hottest_temp=np.max(weeks)
occured_hottest= np.unravel_index(np.argmax(weeks),weeks.shape)
print(f"The Hottest Temp is {Hottest_temp} which occured on week {occured_hottest[0]+1} and day {occured_hottest[1]+1}")  #we do +1 for redability

The Hottest Temp is 42 which occured on week 1 and day 5


## Step 6: Daily Temperature

We analyze how the temperature changes **day-to-day** using `np.diff()` for each week.  
This helps us visualize fluctuations and spot instability.


In [14]:
Temp_change=np.diff(weeks, axis=1)
print("The temperature change is: ",Temp_change)

The temperature change is:  [[  7  -7  12   5  -8]
 [ -7  -1   9 -17  13]
 [ -1 -11  13  -6  -3]
 [-13   5   1 -12  12]
 [  9   2   2 -11  17]
 [  7  -5  10  -9   3]
 [ 18 -12   8  -2 -12]
 [ -3   7 -16  10 -14]
 [  3  -6   4  -3  -5]
 [  2   3  -9  -3   6]]


## Step 7: Sudden Temperature Spikes

We consider a **"spike"** when the temperature increases by **more than 8°C** in a single day.  
We use `np.where()` to detect such spikes and show the week, day, and change.


In [16]:
Spike=np.where(Temp_change>8)
for week,day in zip(*Spike):
    change=weeks[week][day+1] - weeks[week][day]
    print(f"The Spike detected is week- {week+1}, day- {day+1}, with a change of {change}°C")

The Spike detected is week- 1, day- 3, with a change of 12°C
The Spike detected is week- 2, day- 3, with a change of 9°C
The Spike detected is week- 2, day- 5, with a change of 13°C
The Spike detected is week- 3, day- 3, with a change of 13°C
The Spike detected is week- 4, day- 5, with a change of 12°C
The Spike detected is week- 5, day- 1, with a change of 9°C
The Spike detected is week- 5, day- 5, with a change of 17°C
The Spike detected is week- 6, day- 3, with a change of 10°C
The Spike detected is week- 7, day- 1, with a change of 18°C
The Spike detected is week- 8, day- 4, with a change of 10°C


# Final Summary

In this project, we successfully:
- Created synthetic temperature data
- Applied NumPy operations to analyze patterns
- Detected weekly trends and sudden events
- Learned how to use `reshape`, `mean`, `where`, `argmax`, `diff`, and more

---

📂 **Next Step:** pushing this to GitHub and starting my journey on a 28-day warpath!
